### ISSUE TITLE
Create Dropdown: `Edit tasks` and `Delete task` options Light theme

### ISSUE THREAD

**Issue by pdhende** [Erikang20/Kanban-task-management-web-app#23]
This component will be open from the three vertical dots next to the `Add new task` button located on

1. Fron the button located on the header 

![Image](https://github.com/Erikang20/Kanban-task-management-web-app/assets/13842841/caf40eda-7bc3-4403-a97d-c39d6e566df8)

2. from the three vertical dots on a card (Top right): 

![Image](https://github.com/Erikang20/Kanban-task-management-web-app/assets/13842841/0f0e89fc-a928-4f11-8aa4-3d6400bcaff9)

Dark theme related task:  https://github.com/users/Erikang20/projects/2/views/1?pane=issue&itemId=70661901

**Comment by javar10** [comment]
The three dots menu task is done, so this one is ready to be worked on. https://github.com/users/Erikang20/projects/2/views/1?pane=issue&itemId=70662727
