### ISSUE TITLE
Create Header

### ISSUE THREAD

**Issue by javar10** [Erikang20/Kanban-task-management-web-app#39]

**Comment by oyinmi** [comment]
Hi Javar. I have done this already. It's part of my task. Although, you can fetch it after it's been merged and style the button.

**Comment by javar10** [comment]
Oh, ok. I didn't realize this was part of another task. Which task was that? I'll take a look once it's merged and update this task with anything that the header still needs.

**Comment by javar10** [comment]
As I look at some of the other tasks, and what already been merged, it seems this issue isn't necessary anymore as the components of the header seem to have their won tasks.

**Comment by Erikang20** [comment]
Well, there are a couple of things that need to be improved for the header:

* Light/Dark theme
* When the sidebar is hidden/shown the color for the button needs to be displayed accordingly: 
* 
![Screenshot 2024-07-11 at 1 24 25 PM](https://github.com/Erikang20/Kanban-task-management-web-app/assets/13842841/c7978963-18d0-41af-9359-e10ed5614541)
![Screenshot 2024-07-11 at 1 24 29 PM](https://github.com/Erikang20/Kanban-task-management-web-app/assets/13842841/519a8af0-197a-4573-a2db-56edbc2e27df)

Feel free to create a different task or update this to fix those (If you feel like doing them ;) )

**Comment by javar10** [comment]
Ok, I'm gonna hold tight until we have the pull from @oyinmi . Then I'll check-in again about what needs to be done here.
